/**
 * reviewTable.ts
 *
 * Wrappers for the two review-table operations:
 *
 * 1. `writeFixedReviewTableEntries` — fills in the 22-item fixed checklist table
 *    that already exists in the HWPX document body (string-replace only, no XML
 *    re-generation).
 *
 * 2. `runAddReviewTable` — spawns `add_review_table.py` to append a second table
 *    containing ad-hoc extra items or an "이상 없습니다" row.
 *
 * Both are deterministic: same input → same output.
 */

import { readFile, writeFile, rename } from "fs/promises";
import path from "path";
import JSZip from "jszip";
import { runStageCommand, stageCommandToError } from "../stages/commands";
import type { StageError } from "../stages/types";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * An entry for the FIXED 22-item checklist table.
 *
 * itemNumber  : 1–22
 * issueNumbers: comma-separated problem numbers, "전체", "확인" or ""
 */
export interface FixedTableEntry {
  itemNumber: number;
  issueNumbers: string;
}

/**
 * An entry for the SECOND (extra) review table generated by add_review_table.py.
 *
 * description : free-text description of the fix
 * numbers     : comma-separated problem numbers or ""
 */
export interface ExtraTableEntry {
  description: string;
  numbers: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. Fill fixed 22-item checklist table
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Write issue-number values into the fixed 22-row "편집오검 내역표" table.
 *
 * Strategy (mirrors the reviewer agent Phase 6 description):
 *   - The table has 3 columns: 번호 | 항목 | 해당번호
 *   - For each entry, we find the row that contains a text cell matching
 *     the item number and replace the EMPTY third cell with the issue numbers.
 *   - We only REPLACE empty cells to avoid overwriting previous content.
 *     If the cell is already non-empty it is overwritten regardless (idempotent).
 *
 * Operates on `Contents/section0.xml` inside the HWPX zip.
 */
export async function writeFixedReviewTableEntries(
  hwpxPath: string,
  entries: FixedTableEntry[]
): Promise<void> {
  if (entries.length === 0) return;

  const data = await readFile(hwpxPath);
  const zip = await JSZip.loadAsync(data);

  const entry = zip.file("Contents/section0.xml");
  if (!entry) {
    throw mkError("review_table_missing_section", "Contents/section0.xml not found in HWPX", {
      hwpxPath,
    });
  }

  let xml = await entry.async("string");

  for (const { itemNumber, issueNumbers } of entries) {
    xml = setFixedTableCell(xml, itemNumber, issueNumbers);
  }

  zip.file("Contents/section0.xml", xml);

  const tmpPath = hwpxPath + ".tmp";
  const out = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  await writeFile(tmpPath, out);
  await rename(tmpPath, hwpxPath);
}

/**
 * Set the 3rd cell (colAddr="2") in the fixed checklist table row for `itemNumber`.
 *
 * Approach:
 *   1. Find the "편집오검" table start.
 *   2. Scan rows; each row's first text cell contains the item number (1–22).
 *   3. Once the right row is located, replace the content of the 3rd cell's
 *      `<hp:t>` element.
 *
 * Returns mutated XML. No-ops (and logs a warning) if the row cannot be found.
 */
function setFixedTableCell(xml: string, itemNumber: number, value: string): string {
  const tableStart = xml.indexOf("편집오검");
  if (tableStart < 0) return xml; // table not found — skip silently

  const tblOpen = xml.lastIndexOf("<hp:tbl", tableStart);
  const tblClose = xml.indexOf("</hp:tbl>", tblOpen) + "</hp:tbl>".length;

  const tblXml = xml.slice(tblOpen, tblClose);

  // Rows: split by <hp:tr> boundaries
  const rowPattern = /<hp:tr>([\s\S]*?)<\/hp:tr>/g;
  let match: RegExpExecArray | null;
  let newTblXml = tblXml;

  while ((match = rowPattern.exec(tblXml)) !== null) {
    const rowFull = match[0];
    // First <hp:t> in the row is the item number cell
    const firstT = rowFull.match(/<hp:t>(\d+)<\/hp:t>/);
    if (!firstT || parseInt(firstT[1], 10) !== itemNumber) continue;

    // Find the 3rd cell (colAddr="2") in this row — it's the "해당번호" cell
    // Strategy: within the row, take everything after the 2nd </hp:tc>
    let tcCount = 0;
    let searchFrom = 0;
    let thirdTcStart = -1;
    while (tcCount < 2) {
      const tcEnd = rowFull.indexOf("</hp:tc>", searchFrom);
      if (tcEnd < 0) break;
      tcCount++;
      searchFrom = tcEnd + "</hp:tc>".length;
    }
    if (tcCount === 2) {
      thirdTcStart = searchFrom;
    }
    if (thirdTcStart < 0) break;

    // Within the 3rd cell, replace <hp:t>...</hp:t> content
    const thirdTcChunk = rowFull.slice(thirdTcStart);
    const tMatch = thirdTcChunk.match(/<hp:t>[^<]*<\/hp:t>/);
    if (!tMatch) break;

    const newThirdTcChunk = thirdTcChunk.replace(
      /<hp:t>[^<]*<\/hp:t>/,
      `<hp:t>${escapeXml(value)}</hp:t>`
    );
    const newRow = rowFull.slice(0, thirdTcStart) + newThirdTcChunk;
    newTblXml = newTblXml.replace(rowFull, newRow);
    break;
  }

  return xml.slice(0, tblOpen) + newTblXml + xml.slice(tblClose);
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Run add_review_table.py wrapper
// ─────────────────────────────────────────────────────────────────────────────

export interface AddReviewTableOptions {
  /** Absolute path to add_review_table.py */
  scriptPath?: string;
  /** Python executable (default: "python3" on non-Windows, "python" on Windows) */
  pythonCommand?: string;
  timeoutMs?: number;
}

/**
 * Append the second "편집오검 내역표" table using `add_review_table.py`.
 *
 * Pass `extraItems` for the list of additional fixes, or call with no extraItems /
 * empty array to produce the "이상 없습니다" row.
 */
export async function runAddReviewTable(
  hwpxPath: string,
  extraItems?: ExtraTableEntry[],
  opts: AddReviewTableOptions = {}
): Promise<void> {
  const python =
    opts.pythonCommand ?? (process.platform === "win32" ? "python" : "python3");

  const scriptPath =
    opts.scriptPath ??
    path.join(
      path.dirname(path.dirname(path.dirname(path.dirname(__dirname)))),
      ".claude",
      "skills",
      "ngd-exam-review",
      "scripts",
      "add_review_table.py"
    );

  const args: string[] = [scriptPath, hwpxPath];

  if (!extraItems?.length) {
    args.push("--no-issues");
  } else {
    for (const { description, numbers } of extraItems) {
      args.push(numbers ? `${description}:${numbers}` : description);
    }
  }

  const result = await runStageCommand({
    command: python,
    args,
    timeoutMs: opts.timeoutMs ?? 30_000,
  });

  const err = stageCommandToError(result);
  if (err) throw err;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function mkError(
  code: string,
  message: string,
  details?: Record<string, unknown>
): StageError {
  return { code, message, retryable: false, details };
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
